/*!
 * Matomo - DbipUpdater Plugin
 *
 * @link https://franz.agency
 * @license GPL v3+
 * @author Franz und Franz
 * @copyright Franz und Franz
 */

// $(document).ready(function () {
    // The following script was for a manual form with a '.save-settings' button.
    // Matomo's standard settings forms (generated by settings.getSettingsHtmlForm())
    // have their own save buttons and mechanisms, so this specific script might
    // no longer be necessary or might target non-existent elements if the templates
    // are updated to use Matomo's standard form rendering.
    // If specific JS is still needed, it should target elements within the
    // Matomo-generated form structure.

    /*
    $('.dbip-updater-section').on('click', '.save-settings', function () {
        // Automatically refresh the page after saving to make sure the new settings are applied
        $(this).parents('form').on('submit', function () {
            setTimeout(function () {
                window.location.reload();
            }, 1000);
            return true;
        });
    });
    */
// });

// No specific JavaScript needed for standard settings forms at this moment.
// If custom behavior is required, it can be added here, targeting
// appropriate selectors within the plugin's settings views.
